/* --- Generated the 29/10/2018 at 10:47 --- */
/* --- heptagon compiler, version 1.03.00 (compiled thu. may. 3 2:35:29 CET 2018) --- */
/* --- Command line: /usr/local/bin/heptc -target c task_controller.ept --- */

#ifndef TASK_CONTROLLER_H
#define TASK_CONTROLLER_H

#include "task_controller_types.h"
typedef struct Task_controller__task_controller_task_c_window_out {
  int task_c_window;
} Task_controller__task_controller_task_c_window_out;

void Task_controller__task_controller_task_c_window_step(int task_up1,
                                                         int task_down1,
                                                         int task_up2,
                                                         int task_down2,
                                                         int task_s,
                                                         int task_e,
                                                         int task_finish,
                                                         int task_start,
                                                         int task_cold,
                                                         int task_temp_ok,
                                                         int task_eco,
                                                         int task_confort,
                                                         int task_on_lamp,
                                                         int task_on_tv,
                                                         int task_precense,
                                                         int task_push_door,
                                                         int task_push_window,
                                                         int task_v_418,
                                                         int task_v_417,
                                                         int task_pnr_8,
                                                         int task_v_398,
                                                         int task_v_397,
                                                         int task_pnr_7,
                                                         int task_v_362,
                                                         int task_v_361,
                                                         int task_v_360,
                                                         int task_pnr_6,
                                                         int task_v_309,
                                                         int task_v_308,
                                                         int task_v_307,
                                                         int task_pnr_5,
                                                         int task_ck_17_1,
                                                         int task_pnr_4,
                                                         int task_ck_19_1,
                                                         int task_pnr_3,
                                                         int task_ck_21_1,
                                                         int task_pnr_2,
                                                         int task_ck_23_1,
                                                         int task_pnr_1,
                                                         int task_ck_25_1,
                                                         int task_pnr,
                                                         int p_task_c_window,
                                                         int p_task_c_door,
                                                         int p_task_c_tv1,
                                                         int p_task_c_tv2,
                                                         int p_task_c_lamp2,
                                                         int p_task_c_lamp1,
                                                         int p_task_c4,
                                                         int p_task_c3,
                                                         int p_task_c2,
                                                         int p_task_c1,
                                                         int task_c_door,
                                                         int task_c_tv1,
                                                         int task_c_tv2,
                                                         int task_c_lamp2,
                                                         int task_c_lamp1,
                                                         int task_c4,
                                                         int task_c3,
                                                         int task_c2,
                                                         int task_c1,
                                                         Task_controller__task_controller_task_c_window_out* _out);

typedef struct Task_controller__task_controller_task_c_door_out {
  int task_c_door;
} Task_controller__task_controller_task_c_door_out;

void Task_controller__task_controller_task_c_door_step(int task_up1,
                                                       int task_down1,
                                                       int task_up2,
                                                       int task_down2,
                                                       int task_s,
                                                       int task_e,
                                                       int task_finish,
                                                       int task_start,
                                                       int task_cold,
                                                       int task_temp_ok,
                                                       int task_eco,
                                                       int task_confort,
                                                       int task_on_lamp,
                                                       int task_on_tv,
                                                       int task_precense,
                                                       int task_push_door,
                                                       int task_push_window,
                                                       int task_v_418,
                                                       int task_v_417,
                                                       int task_pnr_8,
                                                       int task_v_398,
                                                       int task_v_397,
                                                       int task_pnr_7,
                                                       int task_v_362,
                                                       int task_v_361,
                                                       int task_v_360,
                                                       int task_pnr_6,
                                                       int task_v_309,
                                                       int task_v_308,
                                                       int task_v_307,
                                                       int task_pnr_5,
                                                       int task_ck_17_1,
                                                       int task_pnr_4,
                                                       int task_ck_19_1,
                                                       int task_pnr_3,
                                                       int task_ck_21_1,
                                                       int task_pnr_2,
                                                       int task_ck_23_1,
                                                       int task_pnr_1,
                                                       int task_ck_25_1,
                                                       int task_pnr,
                                                       int p_task_c_window,
                                                       int p_task_c_door,
                                                       int p_task_c_tv1,
                                                       int p_task_c_tv2,
                                                       int p_task_c_lamp2,
                                                       int p_task_c_lamp1,
                                                       int p_task_c4,
                                                       int p_task_c3,
                                                       int p_task_c2,
                                                       int p_task_c1,
                                                       int task_c_tv1,
                                                       int task_c_tv2,
                                                       int task_c_lamp2,
                                                       int task_c_lamp1,
                                                       int task_c4,
                                                       int task_c3,
                                                       int task_c2,
                                                       int task_c1,
                                                       Task_controller__task_controller_task_c_door_out* _out);

typedef struct Task_controller__task_controller_task_c_tv1_out {
  int task_c_tv1;
} Task_controller__task_controller_task_c_tv1_out;

void Task_controller__task_controller_task_c_tv1_step(int task_up1,
                                                      int task_down1,
                                                      int task_up2,
                                                      int task_down2,
                                                      int task_s, int task_e,
                                                      int task_finish,
                                                      int task_start,
                                                      int task_cold,
                                                      int task_temp_ok,
                                                      int task_eco,
                                                      int task_confort,
                                                      int task_on_lamp,
                                                      int task_on_tv,
                                                      int task_precense,
                                                      int task_push_door,
                                                      int task_push_window,
                                                      int task_v_418,
                                                      int task_v_417,
                                                      int task_pnr_8,
                                                      int task_v_398,
                                                      int task_v_397,
                                                      int task_pnr_7,
                                                      int task_v_362,
                                                      int task_v_361,
                                                      int task_v_360,
                                                      int task_pnr_6,
                                                      int task_v_309,
                                                      int task_v_308,
                                                      int task_v_307,
                                                      int task_pnr_5,
                                                      int task_ck_17_1,
                                                      int task_pnr_4,
                                                      int task_ck_19_1,
                                                      int task_pnr_3,
                                                      int task_ck_21_1,
                                                      int task_pnr_2,
                                                      int task_ck_23_1,
                                                      int task_pnr_1,
                                                      int task_ck_25_1,
                                                      int task_pnr,
                                                      int p_task_c_window,
                                                      int p_task_c_door,
                                                      int p_task_c_tv1,
                                                      int p_task_c_tv2,
                                                      int p_task_c_lamp2,
                                                      int p_task_c_lamp1,
                                                      int p_task_c4,
                                                      int p_task_c3,
                                                      int p_task_c2,
                                                      int p_task_c1,
                                                      int task_c_tv2,
                                                      int task_c_lamp2,
                                                      int task_c_lamp1,
                                                      int task_c4,
                                                      int task_c3,
                                                      int task_c2,
                                                      int task_c1,
                                                      Task_controller__task_controller_task_c_tv1_out* _out);

typedef struct Task_controller__task_controller_task_c_tv2_out {
  int task_c_tv2;
} Task_controller__task_controller_task_c_tv2_out;

void Task_controller__task_controller_task_c_tv2_step(int task_up1,
                                                      int task_down1,
                                                      int task_up2,
                                                      int task_down2,
                                                      int task_s, int task_e,
                                                      int task_finish,
                                                      int task_start,
                                                      int task_cold,
                                                      int task_temp_ok,
                                                      int task_eco,
                                                      int task_confort,
                                                      int task_on_lamp,
                                                      int task_on_tv,
                                                      int task_precense,
                                                      int task_push_door,
                                                      int task_push_window,
                                                      int task_v_418,
                                                      int task_v_417,
                                                      int task_pnr_8,
                                                      int task_v_398,
                                                      int task_v_397,
                                                      int task_pnr_7,
                                                      int task_v_362,
                                                      int task_v_361,
                                                      int task_v_360,
                                                      int task_pnr_6,
                                                      int task_v_309,
                                                      int task_v_308,
                                                      int task_v_307,
                                                      int task_pnr_5,
                                                      int task_ck_17_1,
                                                      int task_pnr_4,
                                                      int task_ck_19_1,
                                                      int task_pnr_3,
                                                      int task_ck_21_1,
                                                      int task_pnr_2,
                                                      int task_ck_23_1,
                                                      int task_pnr_1,
                                                      int task_ck_25_1,
                                                      int task_pnr,
                                                      int p_task_c_window,
                                                      int p_task_c_door,
                                                      int p_task_c_tv1,
                                                      int p_task_c_tv2,
                                                      int p_task_c_lamp2,
                                                      int p_task_c_lamp1,
                                                      int p_task_c4,
                                                      int p_task_c3,
                                                      int p_task_c2,
                                                      int p_task_c1,
                                                      int task_c_lamp2,
                                                      int task_c_lamp1,
                                                      int task_c4,
                                                      int task_c3,
                                                      int task_c2,
                                                      int task_c1,
                                                      Task_controller__task_controller_task_c_tv2_out* _out);

typedef struct Task_controller__task_controller_task_c_lamp2_out {
  int task_c_lamp2;
} Task_controller__task_controller_task_c_lamp2_out;

void Task_controller__task_controller_task_c_lamp2_step(int task_up1,
                                                        int task_down1,
                                                        int task_up2,
                                                        int task_down2,
                                                        int task_s,
                                                        int task_e,
                                                        int task_finish,
                                                        int task_start,
                                                        int task_cold,
                                                        int task_temp_ok,
                                                        int task_eco,
                                                        int task_confort,
                                                        int task_on_lamp,
                                                        int task_on_tv,
                                                        int task_precense,
                                                        int task_push_door,
                                                        int task_push_window,
                                                        int task_v_418,
                                                        int task_v_417,
                                                        int task_pnr_8,
                                                        int task_v_398,
                                                        int task_v_397,
                                                        int task_pnr_7,
                                                        int task_v_362,
                                                        int task_v_361,
                                                        int task_v_360,
                                                        int task_pnr_6,
                                                        int task_v_309,
                                                        int task_v_308,
                                                        int task_v_307,
                                                        int task_pnr_5,
                                                        int task_ck_17_1,
                                                        int task_pnr_4,
                                                        int task_ck_19_1,
                                                        int task_pnr_3,
                                                        int task_ck_21_1,
                                                        int task_pnr_2,
                                                        int task_ck_23_1,
                                                        int task_pnr_1,
                                                        int task_ck_25_1,
                                                        int task_pnr,
                                                        int p_task_c_window,
                                                        int p_task_c_door,
                                                        int p_task_c_tv1,
                                                        int p_task_c_tv2,
                                                        int p_task_c_lamp2,
                                                        int p_task_c_lamp1,
                                                        int p_task_c4,
                                                        int p_task_c3,
                                                        int p_task_c2,
                                                        int p_task_c1,
                                                        int task_c_lamp1,
                                                        int task_c4,
                                                        int task_c3,
                                                        int task_c2,
                                                        int task_c1,
                                                        Task_controller__task_controller_task_c_lamp2_out* _out);

typedef struct Task_controller__task_controller_task_c_lamp1_out {
  int task_c_lamp1;
} Task_controller__task_controller_task_c_lamp1_out;

void Task_controller__task_controller_task_c_lamp1_step(int task_up1,
                                                        int task_down1,
                                                        int task_up2,
                                                        int task_down2,
                                                        int task_s,
                                                        int task_e,
                                                        int task_finish,
                                                        int task_start,
                                                        int task_cold,
                                                        int task_temp_ok,
                                                        int task_eco,
                                                        int task_confort,
                                                        int task_on_lamp,
                                                        int task_on_tv,
                                                        int task_precense,
                                                        int task_push_door,
                                                        int task_push_window,
                                                        int task_v_418,
                                                        int task_v_417,
                                                        int task_pnr_8,
                                                        int task_v_398,
                                                        int task_v_397,
                                                        int task_pnr_7,
                                                        int task_v_362,
                                                        int task_v_361,
                                                        int task_v_360,
                                                        int task_pnr_6,
                                                        int task_v_309,
                                                        int task_v_308,
                                                        int task_v_307,
                                                        int task_pnr_5,
                                                        int task_ck_17_1,
                                                        int task_pnr_4,
                                                        int task_ck_19_1,
                                                        int task_pnr_3,
                                                        int task_ck_21_1,
                                                        int task_pnr_2,
                                                        int task_ck_23_1,
                                                        int task_pnr_1,
                                                        int task_ck_25_1,
                                                        int task_pnr,
                                                        int p_task_c_window,
                                                        int p_task_c_door,
                                                        int p_task_c_tv1,
                                                        int p_task_c_tv2,
                                                        int p_task_c_lamp2,
                                                        int p_task_c_lamp1,
                                                        int p_task_c4,
                                                        int p_task_c3,
                                                        int p_task_c2,
                                                        int p_task_c1,
                                                        int task_c4,
                                                        int task_c3,
                                                        int task_c2,
                                                        int task_c1,
                                                        Task_controller__task_controller_task_c_lamp1_out* _out);

typedef struct Task_controller__task_controller_task_c4_out {
  int task_c4;
} Task_controller__task_controller_task_c4_out;

void Task_controller__task_controller_task_c4_step(int task_up1,
                                                   int task_down1,
                                                   int task_up2,
                                                   int task_down2,
                                                   int task_s, int task_e,
                                                   int task_finish,
                                                   int task_start,
                                                   int task_cold,
                                                   int task_temp_ok,
                                                   int task_eco,
                                                   int task_confort,
                                                   int task_on_lamp,
                                                   int task_on_tv,
                                                   int task_precense,
                                                   int task_push_door,
                                                   int task_push_window,
                                                   int task_v_418,
                                                   int task_v_417,
                                                   int task_pnr_8,
                                                   int task_v_398,
                                                   int task_v_397,
                                                   int task_pnr_7,
                                                   int task_v_362,
                                                   int task_v_361,
                                                   int task_v_360,
                                                   int task_pnr_6,
                                                   int task_v_309,
                                                   int task_v_308,
                                                   int task_v_307,
                                                   int task_pnr_5,
                                                   int task_ck_17_1,
                                                   int task_pnr_4,
                                                   int task_ck_19_1,
                                                   int task_pnr_3,
                                                   int task_ck_21_1,
                                                   int task_pnr_2,
                                                   int task_ck_23_1,
                                                   int task_pnr_1,
                                                   int task_ck_25_1,
                                                   int task_pnr,
                                                   int p_task_c_window,
                                                   int p_task_c_door,
                                                   int p_task_c_tv1,
                                                   int p_task_c_tv2,
                                                   int p_task_c_lamp2,
                                                   int p_task_c_lamp1,
                                                   int p_task_c4,
                                                   int p_task_c3,
                                                   int p_task_c2,
                                                   int p_task_c1,
                                                   int task_c3, int task_c2,
                                                   int task_c1,
                                                   Task_controller__task_controller_task_c4_out* _out);

typedef struct Task_controller__task_controller_task_c3_out {
  int task_c3;
} Task_controller__task_controller_task_c3_out;

void Task_controller__task_controller_task_c3_step(int task_up1,
                                                   int task_down1,
                                                   int task_up2,
                                                   int task_down2,
                                                   int task_s, int task_e,
                                                   int task_finish,
                                                   int task_start,
                                                   int task_cold,
                                                   int task_temp_ok,
                                                   int task_eco,
                                                   int task_confort,
                                                   int task_on_lamp,
                                                   int task_on_tv,
                                                   int task_precense,
                                                   int task_push_door,
                                                   int task_push_window,
                                                   int task_v_418,
                                                   int task_v_417,
                                                   int task_pnr_8,
                                                   int task_v_398,
                                                   int task_v_397,
                                                   int task_pnr_7,
                                                   int task_v_362,
                                                   int task_v_361,
                                                   int task_v_360,
                                                   int task_pnr_6,
                                                   int task_v_309,
                                                   int task_v_308,
                                                   int task_v_307,
                                                   int task_pnr_5,
                                                   int task_ck_17_1,
                                                   int task_pnr_4,
                                                   int task_ck_19_1,
                                                   int task_pnr_3,
                                                   int task_ck_21_1,
                                                   int task_pnr_2,
                                                   int task_ck_23_1,
                                                   int task_pnr_1,
                                                   int task_ck_25_1,
                                                   int task_pnr,
                                                   int p_task_c_window,
                                                   int p_task_c_door,
                                                   int p_task_c_tv1,
                                                   int p_task_c_tv2,
                                                   int p_task_c_lamp2,
                                                   int p_task_c_lamp1,
                                                   int p_task_c4,
                                                   int p_task_c3,
                                                   int p_task_c2,
                                                   int p_task_c1,
                                                   int task_c2, int task_c1,
                                                   Task_controller__task_controller_task_c3_out* _out);

typedef struct Task_controller__task_controller_task_c2_out {
  int task_c2;
} Task_controller__task_controller_task_c2_out;

void Task_controller__task_controller_task_c2_step(int task_up1,
                                                   int task_down1,
                                                   int task_up2,
                                                   int task_down2,
                                                   int task_s, int task_e,
                                                   int task_finish,
                                                   int task_start,
                                                   int task_cold,
                                                   int task_temp_ok,
                                                   int task_eco,
                                                   int task_confort,
                                                   int task_on_lamp,
                                                   int task_on_tv,
                                                   int task_precense,
                                                   int task_push_door,
                                                   int task_push_window,
                                                   int task_v_418,
                                                   int task_v_417,
                                                   int task_pnr_8,
                                                   int task_v_398,
                                                   int task_v_397,
                                                   int task_pnr_7,
                                                   int task_v_362,
                                                   int task_v_361,
                                                   int task_v_360,
                                                   int task_pnr_6,
                                                   int task_v_309,
                                                   int task_v_308,
                                                   int task_v_307,
                                                   int task_pnr_5,
                                                   int task_ck_17_1,
                                                   int task_pnr_4,
                                                   int task_ck_19_1,
                                                   int task_pnr_3,
                                                   int task_ck_21_1,
                                                   int task_pnr_2,
                                                   int task_ck_23_1,
                                                   int task_pnr_1,
                                                   int task_ck_25_1,
                                                   int task_pnr,
                                                   int p_task_c_window,
                                                   int p_task_c_door,
                                                   int p_task_c_tv1,
                                                   int p_task_c_tv2,
                                                   int p_task_c_lamp2,
                                                   int p_task_c_lamp1,
                                                   int p_task_c4,
                                                   int p_task_c3,
                                                   int p_task_c2,
                                                   int p_task_c1,
                                                   int task_c1,
                                                   Task_controller__task_controller_task_c2_out* _out);

typedef struct Task_controller__task_controller_task_c1_out {
  int task_c1;
} Task_controller__task_controller_task_c1_out;

void Task_controller__task_controller_task_c1_step(int task_up1,
                                                   int task_down1,
                                                   int task_up2,
                                                   int task_down2,
                                                   int task_s, int task_e,
                                                   int task_finish,
                                                   int task_start,
                                                   int task_cold,
                                                   int task_temp_ok,
                                                   int task_eco,
                                                   int task_confort,
                                                   int task_on_lamp,
                                                   int task_on_tv,
                                                   int task_precense,
                                                   int task_push_door,
                                                   int task_push_window,
                                                   int task_v_418,
                                                   int task_v_417,
                                                   int task_pnr_8,
                                                   int task_v_398,
                                                   int task_v_397,
                                                   int task_pnr_7,
                                                   int task_v_362,
                                                   int task_v_361,
                                                   int task_v_360,
                                                   int task_pnr_6,
                                                   int task_v_309,
                                                   int task_v_308,
                                                   int task_v_307,
                                                   int task_pnr_5,
                                                   int task_ck_17_1,
                                                   int task_pnr_4,
                                                   int task_ck_19_1,
                                                   int task_pnr_3,
                                                   int task_ck_21_1,
                                                   int task_pnr_2,
                                                   int task_ck_23_1,
                                                   int task_pnr_1,
                                                   int task_ck_25_1,
                                                   int task_pnr,
                                                   int p_task_c_window,
                                                   int p_task_c_door,
                                                   int p_task_c_tv1,
                                                   int p_task_c_tv2,
                                                   int p_task_c_lamp2,
                                                   int p_task_c_lamp1,
                                                   int p_task_c4,
                                                   int p_task_c3,
                                                   int p_task_c2,
                                                   int p_task_c1,
                                                   Task_controller__task_controller_task_c1_out* _out);

typedef struct Task_controller__task_controller_out {
  int task_c_window;
  int task_c_door;
  int task_c_tv1;
  int task_c_tv2;
  int task_c_lamp2;
  int task_c_lamp1;
  int task_c4;
  int task_c3;
  int task_c2;
  int task_c1;
} Task_controller__task_controller_out;

void Task_controller__task_controller_step(int task_up1, int task_down1,
                                           int task_up2, int task_down2,
                                           int task_s, int task_e,
                                           int task_finish, int task_start,
                                           int task_cold, int task_temp_ok,
                                           int task_eco, int task_confort,
                                           int task_on_lamp, int task_on_tv,
                                           int task_precense,
                                           int task_push_door,
                                           int task_push_window,
                                           int task_v_418, int task_v_417,
                                           int task_pnr_8, int task_v_398,
                                           int task_v_397, int task_pnr_7,
                                           int task_v_362, int task_v_361,
                                           int task_v_360, int task_pnr_6,
                                           int task_v_309, int task_v_308,
                                           int task_v_307, int task_pnr_5,
                                           int task_ck_17_1, int task_pnr_4,
                                           int task_ck_19_1, int task_pnr_3,
                                           int task_ck_21_1, int task_pnr_2,
                                           int task_ck_23_1, int task_pnr_1,
                                           int task_ck_25_1, int task_pnr,
                                           int p_task_c_window,
                                           int p_task_c_door,
                                           int p_task_c_tv1,
                                           int p_task_c_tv2,
                                           int p_task_c_lamp2,
                                           int p_task_c_lamp1, int p_task_c4,
                                           int p_task_c3, int p_task_c2,
                                           int p_task_c1,
                                           Task_controller__task_controller_out* _out);

#endif // TASK_CONTROLLER_H
